create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10, 2) not null,
  image text,
  category text,
  stock integer default 0,
  created_at timestamp with time zone default now()
);